name: PDS tracks backup

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

env:
  # PDS API Credentials
  PDS_TOKEN: ${{ secrets.PDS_TOKEN }}
  PDS_SECRET: ${{ secrets.PDS_SECRET }}
  PDS_USERNAME: ${{ secrets.PDS_USERNAME }}
  PDS_PASSWORD: ${{ secrets.PDS_PASSWORD }}
  PDS_CUSTOMER_ID: ${{ secrets.PDS_CUSTOMER_ID }}
  # Google Cloud Platform
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  # Metadata Services
  AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
  AIRTABLE_BASE_ID_FRAME: ${{ secrets.AIRTABLE_BASE_ID_FRAME }}
  AIRTABLE_BASE_ID_TRACKS_APP: ${{ secrets.AIRTABLE_BASE_ID_TRACKS_APP }}

jobs:
  build-container:
    name: Build R container
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: ghcr.io/worldfishcenter/peskas.coasts/r-runner-peskas-coasts:latest
          cache-from: type=registry,ref=ghcr.io/worldfishcenter/peskas.coasts/r-runner-peskas-coasts:buildcache
          cache-to: type=registry,ref=ghcr.io/worldfishcenter/peskas.coasts/r-runner-peskas-coasts:buildcache,mode=max

  backup-tracks:
    name: Backup pds tracks data
    needs: build-container
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/worldfishcenter/peskas.coasts/r-runner-peskas-coasts:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set env to production
        if: endsWith(github.ref, '/main')
        run: echo "R_CONFIG_ACTIVE=production" >> $GITHUB_ENV
      - name: Call backup_tracks()
        run: Rscript -e 'coasts::backup_tracks()'